os: linux
language: cpp
sudo: required
dist: trusty
env:
  matrix:
  - DISTRO=ubuntu-16.04
  - DISTRO=centos-7
services:
- docker
before_install:
- docker build docker/${DISTRO} -t dev/sql-parser/${DISTRO}
script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/sql-parser dev/sql-parser/${DISTRO}