language: cpp
sudo: required
dist: trusty
env:
  matrix:
  - DISTRO=ubuntu-16.04 MODE=debug
  - DISTRO=ubuntu-16.04 MODE=release
  - DISTRO=centos-7 MODE=debug
  - DISTRO=centos-7 MODE=release
services:
- docker
before_install:
- docker build docker/${DISTRO} -t dev/sql-parser/${DISTRO}
script:
- if [[ ${MODE} == "debug" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/sql-parser dev/sql-parser/${DISTRO}; fi
- if [[ ${MODE} == "release" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/sql-parser dev/sql-parser/${DISTRO}; fi